name       : sdl1-pango
version    : 0.1.2
release    : 3
source     :
    - http://vorboss.dl.sourceforge.net/project/sdlpango/SDL_Pango/0.1.2/SDL_Pango-0.1.2.tar.gz : 7f75d3b97acf707c696ea126424906204ebfa07660162de925173cdd0257eba4
license    : LGPL-2.0
component  : multimedia.library
summary    : Pango SDL binding
description: |
    Pango SDL binding
builddeps  :
    - pkgconfig(pango)
    - pkgconfig(sdl)
setup      : |
    %patch -p0 < $pkgfiles/0001-Add-aditional-API.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
